[package]
name = "zotgtfs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
chrono-tz = "0.8.5"
color-eyre = "0.6.2"
csv = "1.3.0"
geo = "0.27.0"
geo-types = "0.7.11"
geojson = "0.24.1"
gtfs-rt = "0.4.0"
gtfs-structures = "0.39.1"
polyline = "0.10.1"
prost = "0.12.3"
protobuf = "3.3.0"
rand = "0.8.5"
redis = "0.24.0"
reqwest = {version = "0.11.23", features = ["brotli", "json"]}
rgb = "0.8.37"
serde = { version = "1.0.194", features = ["derive"] }
serde_json = "1.0.111"
tokio = {version = "1.35.1", features = ["full"] }
vincenty-core = "1.0.0"

[[bin]]
name = "downloadstatic"
path = "src/static/download.rs"

[[bin]]
name = "processstatic"
path = "src/static/process.rs"
