name: Deploy on Successful Build

on:
  workflow_run:
    workflows: ["Rust"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Cloudflared
        run: |
          curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared.deb
        shell: bash

      - name: Setup ssh cloudflared config
        run: |
          mkdir -p ~/.ssh
          printf "Host sshtransit03.catenarymaps.org\nProxyCommand /usr/bin/cloudflared access ssh --hostname %%h" > ~/.ssh/config
          echo "${{ secrets.REMOTE_SERVER }}" > ~/.ssh/known_hosts
        shell: bash
        
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
        shell: bash

      - name: SSH
        run: |
          ssh runner@sshtransit03.catenarymaps.org "echo '${{ secrets.SUDO_PASSWD }}' | sudo -S bash -c 'chown -R lolpro11 /opt/zotgtfs; rm /opt/zotgtfs/Cargo.lock'; echo '${{ secrets.SUDO_PASSWD }}' | sudo -S -u lolpro11 bash -c 'cd /opt/zotgtfs; git pull; cargo clean --verbose; cargo build --release --verbose'; echo '${{ secrets.SUDO_PASSWD }}' | sudo -S systemctl restart kactusingest.service kactuslacmta.service kactusmetrolink.service kactusmtarail.service kactuspublic.service kactusserver.service zotgtfsrt.service"
        shell: bash
